version: '3'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile.app1
    ports:
      - "6000:6000"
    env_file:
      - .env
  app2:
    build:
      context: .
      dockerfile: Dockerfile.app2
    ports:
      - "7001:7000"
    env_file:
      - .env

